---
- hosts: localhost
  become: true
#  become_user: root
  tasks:
    - name: install pip boto
      shell: |
        sudo pip install boto 
- hosts: loacalhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  
  vars:
   # volume_size: '13'
    volume_type: 'gp2'
    device_name: '/dev/xvdf'
    zone: 'us-east-2a'
    region: 'us-east-2'
   # instance: "{{ morpheus['customeOptions']['instance_id'] }}"

  tasks:
    - name: Creating a new volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        volume_size: "{{ morpheus['customeOptions']['volume_size'] }}"
        volume_type: "{{ volume_type }}"
        device_name: "{{ device_name }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        tags:
          Name: linux_volume
      register: new_volume

    - name: Attaching created volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        instance: "{{ morpheus['customeOptions']['instance_id'] }}"
        #instance: "id"
        #instance_ids: "id"
        id: "{{ new_volume.volume_id }}"
        device_name: "{{ device_name }}"
        delete_on_termination: true
        region: "{{ region }}"
        zone: "{{ zone}}"
      #loop: {{ ec2.instances }}
      register: attach_volume
