--- 
- become: true
  become_user: Administrator
  hosts: all
  vars:
    ansible_python_interpreter: C:\Python27\python.exe
  tasks: 
    - name: Create a partition with drive letter D and size 5 GiB
      win_partition:
        drive_letter: D
        partition_size: 10 GiB
        disk_number: 1

    - name: Full format the newly created partition as NTFS and label it
      win_format:
        drive_letter: D
        file_system: NTFS
        new_label: Data
        full: True
    
  