--- 
- become: true
  become_user: Administrator
  hosts: all
  vars:
    ansible_python_interpreter: C:\Python27\python.exe
  tasks: 
    - name: Resize previously created partition to it's maximum size and change it's drive letter to E
      win_partition:
        drive_letter: E
        file_system : ntfs
        new_label: data
        disk_number: 1
        offlin: no
    
  