--- 
- become: true
  become_user: Administrator
  hosts: all
  vars:
    ansible_python_interpreter: C:\Python27\python.exe
  tasks: 
    - name: Create Partition
      win_partition:
        drive_letter: D
        file_system : ntfs
        disk_number: 1

    - name: Format Partition    
      win_format:
        drive_letter: D
        file_system: NTFS
        new_label: Data
        full: True
    
  