- hosts: all
  become: yes
  become_user: Administrator
  tasks: 
    diskpart
    select disk 1
    attributes disk clear readonly
    clean
    online disk
    convert gpt
    create partition primary
    format quick fs=ntfs label=Dev
    assign letter=D
