- hosts: all
  become: yes
  become_user: Administrator
  tasks: 
    - name: run multi-lined shell commands
      win_shell: |
          select disk 3 > ./disk.txt
          attributes disk clear readonly >> ./disk.txt
          clean >> ./disk.txt
          online disk >> ./disk.txt
          create partition primary >> ./disk.txt
          format quick fs=ntfs label=test >> ./disk.txt
          assign letter=G >> ./disk.txt
          diskpart /s ./disk.txt