- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Mounting the volume
      shell: |
        sudo mkfs -t ext4 /dev/xvdg
        sudo mkdir /data2
        sudo mount /dev/xvdg /data2
        sudo echo "UUID="$(blkid | sed -n '/xvdg/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data2  ext4  defaults,nofail  0  2" >> /etc/fstab
