---
- hosts: all
  become: true
  become_user: root
  vars:
    device_name: "{{ morpheus['customOptions']['device_name'] }}"
  tasks:
    - name: Mounting the volume
      shell: |
        sudo mkfs -t ext4 "{{ device_name }}"
        sudo mkdir /data
        sudo mount "{{ device_name }}" /data
        sudo echo "UUID="$(blkid | sed -n '/xvdf/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data  ext4  defaults,nofail  0  2" >> /etc/fstab
