--- 
- become: true
  become_user: Administrator
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: C:\Python27\python.exe
  tasks: 
    - name: initialize disk
      win_shell: Initialize-Disk -Number 2

    - name: Partition the created volume
      win_partition:
        drive_letter: E
        partition_size: -1
        disk_number: 2
        offline: no
    - name: Full format the newly created partition as NTFS and label it
      win_format:
        drive_letter: E
        file_system: NTFS
        new_label: Dev
        full: True
    
  