--- 
- become: true
  become_user: Administrator
  hosts: all
  tasks: 
    - name: run multi-lined shell commands
      win_shell: |
         
          echo "" > ./disk.bat
          echo "(echo Rescan" >> ./disk.bat
          echo "select disk 1" >> ./disk.bat
          echo "attributes disk clear readonly" >> ./disk.bat
          echo "clean" >> ./disk.bat
          echo "online disk" >> ./disk.bat
          echo "create partition primary" >> ./disk.bat
          echo "format quick fs=ntfs label=data" >> ./disk.bat
          echo "assign letter=D" >> ./disk.bat
          echo ")  | diskpart" >> ./disk.bat

    - name: Simple batch script
      win_command: "./disk.bat"
    
  