--- 
- become: true
  become_user: Administrator
  hosts: all
  tasks: 
    - name: run multi-lined shell commands
      win_shell: |
          echo "diskpart.exe /s ./disk.txt" > ./disk.bat
          echo "" > ./disk.txt
          echo "select disk 1" > ./disk.txt
          echo "attributes disk clear readonly" >> ./disk.txt
          echo "clean" >> ./disk.txt
          echo "online disk" >> ./disk.txt
          echo "create partition primary" >> ./disk.txt
          echo "format quick fs=ntfs label=data" >> ./disk.txt
          echo "assign letter=D" >> ./disk.txt

    - name: Simple batch script
      win_command: "./disk.bat"
    
  