- hosts: all
  become: yes
  become_user: Administrator
  tasks: 
    - name: Resize previously created partition to it's maximum size and change it's drive letter to E
      community.windows.win_partition:
        drive_letter: E
        disk_number: 2
