--- 
- become: true
  become_user: Administrator
  hosts: all
  vars:
    ansible_python_interpreter: C:\Python27\python.exe
  tasks: 
    - parted:
        device: /dev/sdh
        number: 1
        state: present
    - filesystem:
        fstype: ntfs
        dev: /dev/sdbh
    - mount:
        fstype: ntfs
        src: /dev/sdbh
        path: /data
        state: mounted
    
  