- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Mounting the volume
      shell: |
        sudo mkfs -t ext4 /dev/xvdh
        sudo mkdir /data3
        sudo mount /dev/xvdh /data3
        sudo echo "UUID="$(blkid | sed -n '/xvdh/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data3  ext4  defaults,nofail  0  2" >> /etc/fstab
