- hosts: all
  become: yes
  become_user: Administrator
  tasks: 
    - parted:
        device: /dev/sdi
        number: 2
        flags: [ lvm ]
        state: present
    - filesystem:
        fstype: ntfs
        dev: /dev/sdbi
    - mount:
        fstype: ntfs
        src: /dev/sdbi
        path: /data
        state: mounted
