- hosts: all
  become: yes
  become_user: Administrator
  tasks: 
    - name: run multi-lined shell commands
      win_shell: |
          echo select disk 3 > ./disk.txt
          echo attributes disk clear readonly >> ./disk.txt
          echo clean >> ./disk.txt
          echo online disk >> ./disk.txt
          echo create partition primary >> ./disk.txt
          echo format quick fs=ntfs label=test >> ./disk.txt
          echo assign letter=G >> ./disk.txt
          echo diskpart /s ./disk.txt