--- 
- become: true
  become_user: Administrator
  hosts: all
  tasks: 
    - community.windows.win_partition: 
        disk_number: 2
        drive_letter: E
        file_system: ntfs
        new_label: data
      name: "run multi-lined shell commands"
