- hosts: all
  become: true
  become_user: root
  vars:
    device_name: "{{ morpheus['customOptions']['device_name'] }}"
    directory: "{{ morpheus['customOptions']['directory_name'] }}"
  tasks:
    - name: Mounting the volume
      shell: |
        sudo mkfs -t ext4 "{{ device_name }}"
        sudo mkdir /"{{ directory }}"
        sudo mount "{{ device_name }}" /"{{ directory }}"
        sudo echo " "{{ device_name }}" /"{{ directory }}"  ext4  defaults,nofail  0  2" >> /etc/fstab
