---
- hosts: localhost
  gather_facts: true
  tasks:
    plugin: morpheus_inventory
    groups:
      - name: app
        searchtype: app
        searchstring:
          appname: tomcat
          apptier: App
    morpheus_url: 'https://ec2-3-128-205-101.us-east-2.compute.amazonaws.com'
    morpheus_api_key: 275600ff-dcbe-478d-adf6-4104cbfc0bb8
