- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - name: fetch host data
      fetch:
        src: "{{ ansible_env.INSTANCE_HOSTNAME }} & {{ ansible_env.IP_INTERNAL }}"
        register: slavehost
        dest: /etc/ansible/node_ip/host_ip-{{ slavehost }}
