
- hosts: app
  vars:
      IP: "{{ ansible_env.IP_INTERNAL }}" 
      HOSTNAME: "{{ ansible_env.INSTANCE_HOSTNAME }}" 
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: "{{ ansible_default_ipv4.address }}"  
