
- hosts: app
#  vars:
#    IP: "{{ ansible_env.IP_INTERNAL }}" 
#    HOSTNAME: "{{ ansible_env.INSTANCE_HOSTNAME }}" 
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: "{{ ansible_default_ipv4.address }}"  
    - name: Echo my_env_var
      shell: "echo $MY_ENV_VARIABLE"
      environment:
        PATH: "{{ansible_env.INSTANCE_HOSTNAME}}:{{ansible_env.IP_INTERNAL}}" 

    - name: Echo my_env_var again
      shell: "echo $MY_ENV_VARIABLE" 
