
- hosts: app
#  vars:
#    IP: "{{ ansible_env.IP_INTERNAL }}" 
#    HOSTNAME: "{{ ansible_env.INSTANCE_HOSTNAME }}" 
  gather_facts: true
  tasks:
    - local_action: 
        module: copy
        content: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
        dest: /etc/ansible/node_ip/host_ip
