- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
      register: HOST_DETAILS
    - name: fetch host data
      fetch: 
        src: {{ HOST_DETAILS }}
        dest: "/etc/ansible/node_ip/host_ip"
