- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: " export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }} "
    - name: get jstack                                                                        
      shell: echo " export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }} " 
      register: jstackOut
