
- hosts: app
  become: true
#  vars:
#    IP: "{{ ansible_env.IP_INTERNAL }}" 
#    HOSTNAME: "{{ ansible_env.INSTANCE_HOSTNAME }}" 
  gather_facts: true
  tasks:
    - debug:
        msg: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
    
