- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
      register: HOST_DETAILS
    - fetch:
        content: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
        dest: /tmp/fetched

