- hosts: app
  gather_facts: true
  tasks:
    - name: export environment vars
      command: /bin/sh /etc/profile.d/morpheus.sh
    - name: Make empty list for tomcat ips
      set_fact:
        tomcat_ips: []
    - name: Assemble list of tomcat ips
      set_fact: 
        tomcat_ips: "{{ tomcat_ips + [ item.value ] }}"
      when: "'tomcat_IP' in item.key"
      loop: "{{ lookup('dict', ansible_env) }}"
    - name: Make empty list for apache ips
      set_fact:
        apache_ips: []
    - name: Assemble list of apache ips
      set_fact: 
        apache_ips: "{{ apache_ips + [ item.value ] }}"
      when: "'apache_IP' in item.key"
      loop: "{{ lookup('dict', ansible_env) }}"
