
- hosts: app
#  vars:
#    IP: "{{ ansible_env.IP_INTERNAL }}" 
#    HOSTNAME: "{{ ansible_env.INSTANCE_HOSTNAME }}" 
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: " export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}" >> /etc/ansible/node_ip/host_ip
