- hosts: app
  become: yes
  become_user: root
  gather_facts: true
  tasks:
    - ping:
    - debug:
        msg: "export {{ ansible_env.INSTANCE_HOSTNAME }}={{ ansible_env.IP_INTERNAL }}"
        
    - name: create file
      file:
        dest: /tmp/details
        state: touch
      delegate_to: localhost
