- hosts: all
  become: true
  tasks:
    - name:  Build nginx 
      shell: |
        sudo yum install -y aws-cfn-bootstrap
        sudo mkfs -t ext4 /dev/xvdf
        mkdir /data
        sudo mount /dev/xvdf /data
        sudo echo "UUID="$(blkid | sed -n '/xvdf/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data  ext4  defaults,nofail  0  2" >> /etc/fstab
