- hosts: all
  tasks:
  #  - name: Install Nano
  #    command: sudo yum install nano 
    - debug:
          msg: "System IP {{ ansible_env.IP_INTERNAL }} has hostname {{ aansible_env.INSTANCE_HOSTNAME }}"
