- hosts: all
  tasks:
  #  - name: Install Nano
  #    command: sudo yum install nano 
    - local_action: 
            module: copy 
            content: " {{ ansible_env.INSTANCE_HOSTNAME }}: {{ ansible_env.IP_INTERNAL }} "
            dest: /opt/morpheus/.local/host_ip.txt    
