- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install or update pip
      community.general.easy_install:
        name: pip
        state: latest
    - name: install pip and boto
      shell: |
        sudo pip install boto 
