---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install Python-pip
       package: name='python2-pip' state=latest
       
    - name: install pip and boto
      shell: |
        sudo pip install boto
