---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Install Python-pip for apt
       package: name='python-pip' state=latest
       when: ansible_distribution == "Ubuntu"

    - name: Install Python-pip for YUM
      package: name='python2-pip' state=latest
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
       
    - name: install pip and boto
      shell: |
        sudo pip install boto
