
- hosts: all
  become: yes
  become_user: root
  tasks:
     - name: install Python Pip
       package: name=python-pip state=latest
       
     - name: install boto
       shell: |
         sudo pip install boto
