---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: install pip and boto
      shell: |
        sudo apt-get install python-pip -y
        sudo pip install boto || pip install -U boto
