- hosts: all
  tasks: 
    - name: Ensure 7-Zip is installed via Chocolatey
      win_chocolatey:
        name: 7zip
        state: present
    - win_shell: choco install postgresql13 --params '/Password:test' --ia '--serverport 5433'
