- hosts: unassigned
  tasks:        
    #- win_shell: choco install postgresql13 --params '/Password:test' --ia '--serverport 5433'
    - name: Ensure PSQL is installed via Chocolatey
      win_chocolatey:
        name: postgresql13
        state: present
    - win_shell: choco install postgresql13 --params '/Password:test' --ia '--serverport 5433'
