- hosts: all
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
        
    - win_shell: choco install postgresql13 --params '/Password:root' --ia '--serverport 5433' -y --force
