- hosts: unassigned
  tasks:        
    - name: Ensure PSQL is installed via Chocolatey
      ansible.windows.win_shell: choco install postgresql13 --params '/Password:test' --ia '--serverport 5433'
