- hosts: all
  tasks:
      
    - name: Ensure PSQL is installed via Chocolatey
      win_chocolatey:
        name: postgresql13 --params '/Password:Root' --ia '--serverport 5433'
        state: present
