--- 
- hosts: all
  become: yes
  become_user: root
  tasks: 
    - name: "Redis-cli install"
      shell: |
          sudo apt-get install redis-tools
          
    - name: "Document DB Client install"
      shell: |
          echo "----------------------------------"
          pwd
          echo "----------------------------------"
          sudo apt-get update -y
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
          echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
          sudo apt-get update -y
          sudo apt-get install -y mongodb-org-shell
          wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
