--- 
- hosts: all
  become: yes
  become_user: root
  vars:
    DOCDBURL: "{{ morpheus['customOptions']['docdburl'] }}"
  tasks: 
    - name: "Redis-cli install"
      shell: |
          sudo apt-get install redis-tools -y
          sudo apt-get update
          sudo apt-get install stunnel4
          sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
          pwd
          wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
        
    - name: "Redis-cli install -2 "    
      shell: |
          touch /etc/stunnel/redis-cli.conf
          cat <<EOF > /etc/stunnel/redis-cli.conf
          [redis-client]
          client = yes
          accept = 127.0.0.1:6379
          connect = "{{ DOCDBURL }}":6379
          [redis-cli-replica]
          client = yes
          accept = 127.0.0.1:6380
          connect = ssltest-002.ssltest.wif0lh.use1.cache.amazonaws.com:6379
          EOF
          sudo stunnel /etc/stunnel/redis-cli.conf
    - name: "Mongod client instalation"
      shell: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell
