--- 
- hosts: all
  become: yes
  become_user: root
  tasks: 
    - name: "Redis-cli install"
      shell: |
          sudo apt-get install redis-tools -y
          sudo apt-get update
          sudo apt-get install stunnel4
      replace:
        path: /etc/default/stunnel4
        regexp: 'ENABLED=0'
        replace: "ENABLED=1"
      shell: |
          touch /etc/stunnel/redis-cli.conf
          cat <<EOF > /etc/stunnel/redis-cli.conf
          [redis-client]
          client = yes
          accept = 127.0.0.1:6379
          connect = master.redis-replica.eqnukq.use2.cache.amazonaws.com:6379
          [redis-cli-replica]
          client = yes
          accept = 127.0.0.1:6380
          connect = ssltest-002.ssltest.wif0lh.use1.cache.amazonaws.com:6379
          EOF
          sudo stunnel /etc/stunnel/redis-cli.conf
