- hosts: all
  tasks:
    - name: Install Soanr
      shell: |
        sudo yum update -y
        echo -e "sonarqube\nsonarqube" | sudo passwd ec2-user
        sudo amazon-linux-extras install postgresql9.6 -y
        sudo yum update -y
        sudo yum install -y postgresql-server.x86_64
        sudo systemctl enable postgresql.service
        sudo /usr/bin/postgresql-setup --initdb
        sudo systemctl start postgresql
        sudo -u postgres -- psql -c "CREATE USER sonar WITH ENCRYPTED PASSWORD 'sonar_password'"
        sudo -u postgres -- psql -c "CREATE DATABASE sonarqube"
        sudo -u postgres -- psql -c "GRANT ALL PRIVILEGES ON DATABASE sonarqube to sonar"
        sudo sed -i '$ a local all sonar md5' /var/lib/pgsql/data/pg_hba.conf
        sudo sed -i 's/ident/md5/' /var/lib/pgsql/data/pg_hba.conf
        sudo systemctl restart postgresql
        sudo groupadd sonar
        sudo useradd -c "Sonar System User" -d /opt/sonarqube -g sonar -s /bin/bash sonar
        echo -e "sonarqube\nsonarqube" | sudo passwd sonar
        sudo usermod -a -G sonar ec2-user
        echo -e "sonarqube" | exec su -l $USER
        curl -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
        tar zxf openjdk-11.0.1_linux-x64_bin.tar.gz
        sudo mv jdk-11.0.1 /usr/local/
        sudo chmod -R 755 /usr/local/jdk-11.0.1
        sudo sed -i '$ a export JAVA_HOME=/usr/local/jdk-11.0.1\nexport PATH=$JAVA_HOME/bin:$PATH' /etc/profile
        source /etc/profile
        wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.5.0.37579.zip
        unzip sonarqube-8.5.0.37579.zip
        sudo mkdir /opt/sonarqube
        sudo mv -v sonarqube-8.5.0.37579/* /opt/sonarqube
        sudo chown -R sonar:sonar /opt/sonarqube
        sudo chmod -R 775 /opt/sonarqube
        sudo mkdir /home/data
        sudo mkdir /home/temp
        sudo chown -R sonar:sonar /home/data
        sudo chmod -R 775 /home/data
        sudo chown -R sonar:sonar /home/temp
        sudo chmod -R 775 /home/temp
        sudo sed -i 's/#RUN_AS_USER=/RUN_AS_USER=sonar/' /opt/sonarqube/bin/linux-x86-64/sonar.sh
        sudo sed -i 's/#sonar.jdbc.username=/sonar.jdbc.username=sonar/' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's/#sonar.jdbc.password=/sonar.jdbc.password=sonar_password/' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's+#sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube?currentSchema=my_schema+sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube+' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's/#sonar.web.port=9000/sonar.web.port=8080/' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's+#sonar.web.context=+sonar.web.context=/sonarqube+' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's+#sonar.path.data=data+sonar.path.data=/home/data+' /opt/sonarqube/conf/sonar.properties
        sudo sed -i 's+#sonar.path.temp=temp+sonar.path.temp=/home/temp+' /opt/sonarqube/conf/sonar.properties
        sudo sed -i '$ a * soft nproc 65535\n* hard nproc 65535\n* soft nofile 65535\n* hard nofile 65535' /etc/security/limits.conf
        sudo sed -i '$ a vm.max_map_count=262144\nfs.file-max=65535' /etc/sysctl.conf
        sudo sysctl -p

        echo -e "sonarqube" | /opt/sonarqube/bin/linux-x86-64/sonar.sh console