- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Touch a file
      file:
        path: "/tmp/test"
        state: touch
    - name: copy content to file
      copy:
        content: "{{ inventory_HOSTNAME }} = {{ ansible_env.IP_INTERNAL }}"
        dest: "/tmp/test"
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/"
        flat: yes
