- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Touch a file
      file:
        path: "/tmp/test"
        state: touch
     
    - name: registering values
      cmd: echo " export {{ansible_env.INSTANCE_HOSTNAME}} = {{ansible_env.IP_INTERNAL}} " 
      register: hostdetails
      
    - name: copy content to file
      copy:
        content: "{{ hostdetails.stdout }}"
        dest: "/tmp/test"
    
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/"
        flat: yes
