- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Touch a file
      file:
        path: "/tmp/test"
        state: touch
     
    - name: rigistering values
      shell: echo " export ${INSTANCE_HOSTNAME}=${INTERNAL} " 
      register: hostdetails
      
    - name: copy content to file
      copy:
        content: "{{ hostdetails.stdout }}"
        dest: "/tmp/test"
    
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/"
        flat: yes
