- hosts: app
  tasks: 
     - name: Add IP address of all hosts to all hosts
          lineinfile: 
            dest: /etc/hosts
            line: '{{ hostvars[item]["ansible_host"] }} {{ hostvars[item]["ansible_hostname"] }} {{ hostvars[item]["ansible_nodename"] }}'
            state: present
          with_items: groups['all']
