- hosts: app
  tasks: 
    
    - name: Update the /etc/hosts file with node name
        tags: etchostsupdate
        become: yes
        become_user: root
        lineinfile:
          dest: "/etc/hosts"
          regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
          line: "{{ inventory_hostname }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
          state: present
          backup: yes
        register: etchostsupdate
        when: inventory_hostname != "{{ item }}" or inventory_hostname == "{{ item }}"
        with_items: "{{groups['launched']}}"
