- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Touch a file
      file:
        path: "/tmp/test"
        state: touch
     
    - name: SAVING VALUES IN FILE USING SHELL
      shell: echo " export ${INSTANCE_HOSTNAME}=${ip_INTERNAL} " > /tmp/test
    
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/{{ inventory_hostname }}.sh"
        flat: yes
