- hosts: all
  gather_facts: true
  tasks:
    - ping:
    - name: debuging hostname
      debug:
        msg: "{{ ansible_hostname }}"
      register: hostdetails  

    - name: debuging ip address
      debug:
        msg: "{{ ansible_hostname }}"
      register: hostip
  environment: 
     newhost: "{{ hostip.stdout }}"  
