- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - copy:
        content: " export {{ ansible_env.INSTANCE_HOSTNAME }} = {{ ansible_env.IP_INTERNAL }} "
        dest: /tmp/test
      delegate_to: localhost
      run_once: true 
