- hosts: app
  gather_facts: true
  tasks:
    - ping:
    - name: registering info 
      shell: echo " export {{ ansible_env.INSTANCE_HOSTNAME }} = {{ ansible_env.IP_INTERNAL }} "
      register: jstackOut 

