- hosts: app
  gather_facts: true
  become_user: wulabs
  tasks:
    - name: Touch a file
      file:
        path: "/home/wulabs/test"
        state: touch
     
    - name: SAVING VALUES IN FILE USING SHELL
      shell: echo "export ${INSTANCE_HOSTNAME^^}=${IP_INTERNAL}" > /home/wulabs/test
    
    
- hosts: app
  gather_facts: true
  become: true
  tasks:
    - name: fetch file from remote host to masternode
      fetch:
        src: "/home/wulabs/test"
        dest: "node_ip/{{ inventory_hostname }}.sh"
        flat: yes


- hosts: app
  gather_facts: true
  tasks:
    - name: Execute the script
      command: sh /var/opt/morpheus/morpheus-ui/repo/git/d2702c84b01370f86d9a84919866f4d4/node_ip/*.sh
