- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Touch a file
      file:
        path: "/tmp/test"
        state: touch
    - name: copy content to file
      copy:
        content: "{{ ansible_default_ipv4.address }} "
        dest: "/tmp/test"
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/"
