- hosts: app
  gather_facts: true
  become_user: wulabs
  tasks:
    - name: Touch a file
      file:
        path: "/home/wulabs/test"
        state: touch
     
    - name: SAVING VALUES IN FILE USING SHELL
      shell: echo "export ${INSTANCE_HOSTNAME^^}=${IP_INTERNAL}" > /home/wulabs/test
    
    
- hosts: app
  become: true
  tasks:
    - name: fetch file from remote host to masternode
      fetch:
        src: "/home/wulabs/test"
        dest: "node_ip/{{ inventory_hostname }}.sh"
        flat: yes


- hosts: app
  become: true
  tasks:
    - name: Another symbolic mode example, adding some permissions and removing others
      copy:
        src: /var/opt/morpheus/morpheus-ui/repo/git/d2702c84b01370f86d9a84919866f4d4/node_ip/*.sh
        dest: "/home/wulabs/test"
        
- hosts: app
  tasks:        
    - name: Run a script with arguments (free form)
      script: sh /home/wulabs/test/*.sh
