- hosts: all
  gather_facts: true
  become: true
  tasks:
    -name: create file
     file: 
       path: "/tmp/test"
       state: touch
    - name: copy content to file
      copy:
        content: "{{ ansible_env.IP_INTERNAL }} "
        dest: "/tmp/test"
    - name: fetch file from remote host to masternode
      fetch:
        src: "/tmp/test"
        dest: "node_ip/"
