- hosts: sonar7
  gather_facts: true
  become_user: wulabs
  tasks:
    - name: Touch a file
      file:
        path: "/home/wulabs/test"
        state: touch
    - name: create directory 
      file:
        path: "/home/wulabs/testdir"
        state: directory
      
    - name: SAVING VALUES IN FILE USING SHELL
      shell: echo "export $(echo ${INSTANCE_HOSTNAME} | tr '[:lower:]' '[:upper:]')=${IP_INTERNAL}" > /home/wulabs/test
    
    
- hosts: sonar7
  become: true
  tasks:
    - name: fetch file from remote host to masternode
      fetch:
        src: "/home/wulabs/test"
        dest: "node_ip/{{ inventory_hostname }}.sh"
        flat: yes



- hosts: sonar7
  become: true
#  become_user: root
  tasks:
    - name: copy file to remote host
      copy:
        src: "/var/opt/morpheus/morpheus-ui/repo/git/d2702c84b01370f86d9a84919866f4d4/node_ip/"
        dest: "/home/wulabs/testdir"

    - name: writing file to /etc/profile.d/morpheus.sh
      shell: cat /home/wulabs/testdir/*.sh >> /etc/profile.d/morpheus.sh
