- hosts: app
  gather_facts: true
  become_user: wulabs
  tasks:
    - name: Touch a file
      file:
        path: "/home/wulabs/test"
        state: touch
        
   # - name: Get the region from the EC2 instance
   #   shell: /usr/bin/ec2metadata --availability-zone | sed 's/.$//'
   #   register: region
   #   ignore_errors: True
      
    - name: SAVING VALUES IN FILE USING SHELL
      shell: echo "export $(echo ${INSTANCE_HOSTNAME} | tr '[:lower:]' '[:upper:]')=${IP_INTERNAL}" > /home/wulabs/test
    
    
- hosts: app
  become: true
  tasks:
    - name: fetch file from remote host to masternode
      fetch:
        src: "/home/wulabs/test"
        dest: "node_ip/{{ inventory_hostname }}.sh"
        flat: yes



- hosts: app
  become: true
  tasks:
    - name: copy file to remote host
      template:
        src: "/var/opt/morpheus/morpheus-ui/repo/git/d2702c84b01370f86d9a84919866f4d4/node_ip/*.sh"
        dest: "/home/wulabs/test/"

    - name: writing file to /etc/profile.d/morpheus.sh
      shell: cat /home/wulabs/test/*.sh >> /home/wulabs/morpheus.sh
