---
- hosts: ubuntu.localdomain  # put localhost.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  
  vars:
    volume_size: "{{ morpheus['customOptions']['volume_size'] }}"
    volume_type: "{{ morpheus['customOptions']['volume_type'] }}"
    device_name: "{{ morpheus['customOptions']['device_name'] }}"
    zone: "{{ morpheus['customOptions']['zone'] }}"
    region: "{{ morpheus['customOptions']['region'] }}"
    instance: "{{ morpheus['customOptions']['instance_id'] }}"
    encryption: "{{ morpheus['customOptions']['encryption'] }}"

  tasks:
    - name: Creating a new volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        volume_size: "{{ volume_size }}"
        volume_type: "{{ volume_type }}"
        device_name: "{{ device_name }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        encrypted: "{{ encryption }}"
        kms_key_id: 9a5444a1-7b32-4f45-bc21-09f45e32026d
        tags:
          Name: linux_volume
      register: new_volume      

    - name: Attaching created volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        instance: "{{ instance }}"
        id: "{{ new_volume.volume_id }}"
        device_name: "{{ device_name }}"
        delete_on_termination: true
        region: "{{ region }}"
        zone: "{{ zone }}"
      register: attach_volume
