---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install bottle python package
      pip:
        name: bottle
    - name: install pip and boto
      shell: |
        sudo pip install boto 
        
- hosts: all  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  
  vars:
    volume_size: "{{ morpheus['customOptions']['volume_size'] }}"
    volume_type: 'gp2'
    device_name: '/dev/xvdf'
    zone: 'us-east-2a'
    region: 'us-east-2'
    instance: "{{ morpheus['customOptions']['instance_id'] }}"

  tasks:
    - name: Creating a new volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        volume_size: "{{ volume_size }}"
        volume_type: "{{ volume_type }}"
        device_name: "{{ device_name }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        tags:
          Name: linux_volume
      register: new_volume

    - name: Attaching created volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        instance: "{{ instance }}"
        id: "{{ new_volume.volume_id }}"
        device_name: "{{ device_name }}"
        delete_on_termination: true
        region: "{{ region }}"
        zone: "{{ zone }}"
      register: attach_volume
    
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Mounting the volume
      shell: |
        sudo mkfs -t ext4 /dev/xvdf
        sudo mkdir /data2
        sudo mount /dev/xvdf /data2
        sudo echo "UUID="$(blkid | sed -n '/xvdf/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data2  ext4  defaults,nofail  0  2" >> /etc/fstab
