- hosts: all
  become : true
  become_user : root
  tasks:
    - name: create a new volume
      ec2_vol:
        volume_size: '10'
        volume_type: 'gp2'
        region: 'us-east-2'
        zone: 'us-east-2a'
        register: new_volume
        delete_on_termination: true

    - name: format and mount the volume
      ec2_vol:
        file_system: ext4

    - name: Attach volume to instance
      ec2_vol: 
        device_name: '/dev/app'
        delete_on_termination: true
        region: 'us-east-2'
        zone: 'us-east-2a'
        register: attach_volume
