---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: false  # don't gather facts against localhost
  become: yes 
  
  tasks: 
    - name: Creating a Volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        instance: i-076e45ebf9ac81282
        volume_size: 10
        device_name: /dev/xvdf
        region: us-east-2
        zone: us-east-2a
        volume_type: gp2
      register: ec2_vol
 
    - name: Printing the volume information
      debug: var=ec2_vol
