---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           #- chocolatey-core.extension
           #- chocolatey
           - python2
           - pip
          state: present
    - win_shell: pip.exe install boto
