---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           #- chocolatey-core.extension
           - chocolatey
           - python2
           - pip
          state: present
    - win_shell: pip.exe install boto
  
- hosts: all  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: false  # don't gather facts against localhost
  become: yes
  become_user: sudo
  
  vars:
    volume_size: '10'
    volume_type: 'gp2'
    device_name: '/dev/xvdf'
    zone: 'us-east-2a'
    region: 'us-east-2'
    instance: i-076e45ebf9ac81282
    #ansible_python_interpreter: 'C:\Python27\python.exe

  tasks:
    - name: create a new volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
        instance: "{{ instance }}"
        #ansible_python_interpreter: "{{ ansible_python_interpreter }}"
        volume_size: "{{ volume_size }}"
        volume_type: "{{ volume_type }}"
        device_name: "{{ device_name }}"
        region: "{{ region }}"
        file_system: NTFS
        zone: "{{ zone }}"
        tags:
          Name: windows_volume
        delegate_to: localhost
      register: ec2_vol
