---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  
- hosts: all  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: true  # don't gather facts against localhost
  
  vars:
    volume_size: '10'
    volume_type: 'gp2'
    mount_path: 'D:\'
    zone: 'us-east-2a'
    region: 'us-east-2'

  tasks:
    - name: create a new volume
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_b') }}"
        volume_size: "{{ volume_size }}"
        volume_type: "{{ volume_type }}"
        mount_path: "{{ mount_path }}"
        region: "{{ region }}"
        file_system: NTFS
        zone: "{{ zone }}"
        tags:
          Name: windows_volume
      register: new_volume

    - name: Ensure volume attachment
      ec2_vol:
        aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
        aws_secret_key: "{{ lookup('cypher','secret=secret/ans_b') }}"
        instance: "{{ inventory_hostname }}"
        #instance: ""
        id: "{{ new_volume.volume_id }}"
        mount_path: "{{ mount_path }}"
        delete_on_termination: true
        region: "{{ region }}"
        zone: "{{ zone }}"
      register: attach_volume
    
- hosts: all
  become: true
  become_user: Administrator
  tasks:
    - name: Partition the created volume
      win_partition:
        drive_letter: D
        partition_size: -1
        disk_number: 1
