- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks: 
    - amazon.aws.ec2_vol:
        instance: "{{ morpheus.instance }}"
        volume_size: 10
        volume_type: gp2
        region: us-east-2
        zone: us-east-2a
        file_system: ext4
        device_name: /dev/app
        delete_on_termination: true
