---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: install pip and boto
      shell: |
        sudo yum install python2-pip -y
        sudo pip install boto 

- hosts: all  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  
  vars:
    volume_size: '8'
    volume_type: 'gp2'
    device_name: '/dev/xvdf'
    zone: 'us-east-2a'
    region: 'us-east-2'
    instance: "{{ ansible_env.instanceid }}"

  tasks:
    - name: Type Debug 1
      debug:
        msg: instance
    
    # - name: Type Debug 2
    #   debug:
    #     msg: {{ ansible_env.instanceid }}

    - name: Type Debug 3
      debug:
        msg: "{{ ansible_env.instanceid }}"

    - name: Type Debug 4
      debug:
        msg: "{{ servers.externalId }}"
      
    - name: Type Debug 5
      debug:
        msg: "{{ externalId }}"

    - name: Type Debug 6
      debug:
        msg: servers.externalId
      
    - name: Type Debug 7
      debug:
        msg: externalId

#     - name: Creating a new volume
#       ec2_vol:
#         aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
#         aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
#         volume_size: "{{ volume_size }}"
#         volume_type: "{{ volume_type }}"
#         device_name: "{{ device_name }}"
#         region: "{{ region }}"
#         zone: "{{ zone }}"
#         tags:
#           Name: linux_volume
#       register: new_volume

#     - name: Attaching created volume
#       ec2_vol:
#         aws_access_key: "{{ lookup('cypher','secret=secret/ans_a') }}"
#         aws_secret_key: "{{ lookup('cypher','secret=secret/ans_s') }}"
#         instance: "{{ item.id }}"
#         #instance_ids: "i-09a2b2a1e872601cf"
#         id: "{{ new_volume.volume_id }}"
#         device_name: "{{ device_name }}"
#         delete_on_termination: true
#         region: "{{ region }}"
#         zone: "{{ zone }}"
#       loop: {{ ec2.instances }}
#       register: attach_volume
    
# - hosts: all
#   become: true
#   become_user: root
#   tasks:
#     - name: Mounting the volume
#       shell: |
#         sudo mkfs -t xfs /dev/xvdf 
#         sudo yum install xfsprogs
#         sudo mkdir /data
#         sudo mount /dev/xvdf /data
#         sudo echo "UUID="$(blkid | sed -n '/xvdf/s/.*UUID=\"\([^\"]*\)\".*/\1/p')" /data  xfs  defaults,nofail  0  2" >> /etc/fstab
