- hosts: all
  become : true
  become_user : root
  tasks:
   - name: create a new volume
   - ec2_vol:
       volume_size: 10
       volume_type: gp2
       region: us-east-2
       zone: us-east-2a
       file_system: ext4
       device_name: /dev/app
       region: us-east-2
       zone: us-east-2a
       delete_on_termination: true
