---
# tasks file for volume
---

- name: Type Debug 1
  ignore_errors: yes
  debug:
    msg: "{{ instanceid }}"

- name: Type Debug 2
  ignore_errors: yes
  debug:
    msg: {{ instanceid }}

- name: Type Debug 3
  ignore_errors: yes
  debug:
    msg: "{{ ansible_env.INSTANCE_ID }}"

- name: Type Debug 4
  ignore_errors: yes
  debug:
    msg: "{{ servers.externalId }}"
  
- name: Type Debug 5
  ignore_errors: yes
  debug:
    msg: "{{ externalId }}"

- name: Type Debug 6
  ignore_errors: yes
  debug:
    msg: servers.externalId
  
- name: Type Debug 7
  ignore_errors: yes
  debug:
    msg: externalId